/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GrantedAuthority } from './';

/**
 * @export
 * @interface User
 */
export interface User {
    /**
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * @type {string}
     * @memberof User
     */
    role?: UserRoleEnum;
    /**
     * @type {boolean}
     * @memberof User
     */
    locked?: boolean;
    /**
     * @type {boolean}
     * @memberof User
     */
    enabled?: boolean;
    /**
     * @type {string}
     * @memberof User
     */
    createdAt?: string;
    /**
     * @type {string}
     * @memberof User
     */
    updatedAt?: string;
    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonLocked?: boolean;
    /**
     * @type {Array<GrantedAuthority>}
     * @memberof User
     */
    authorities?: GrantedAuthority[];
    /**
     * @type {boolean}
     * @memberof User
     */
    credentialsNonExpired?: boolean;
    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonExpired?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum UserRoleEnum {
    Admin = 'ADMIN',
    User = 'USER',
}
